spring.application.name=mymovies-backend

# === DATASOURCE: PostgreSQL ===
spring.datasource.url=jdbc:postgresql://localhost:5432/mymoviesdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === Server ===
server.port=8080

# === Credenziali admin lato backend (solo sviluppo locale) ===
# Sovrascrivibili con variabili d'ambiente: MMC_ADMIN_USER / MMC_ADMIN_PASSWORD
mmc.admin.user=user
mmc.admin.password=1234


# === H2 (disattivato) ===
# Tutte queste righe sotto vanno commentate con # (non con !)
# spring.datasource.url=jdbc:h2:mem:mymoviesdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
